linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  disable-all: true
  enable:
    - govet
    - ineffassign
    - unused
    - gofmt
    - goimports

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec

    # Temporarily exclude error checking until we properly fix all instances
    - linters:
        - errcheck
      text: "Error return value.*is not checked"

    # Exclude select simplification warnings
    - linters:
        - gosimple
      text: "S1000"

    # Exclude unused append warnings
    - linters:
        - staticcheck
      text: "SA4010"

  # Maximum issues count per one linter
  max-issues-per-linter: 0

  # Maximum count of issues with the same text
  max-same-issues: 0

run:
  timeout: 5m
  tests: true
