{
 "title": "Ethereum Kiln Overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "12s",
 "templating": {
  "list": [
   {
    "name": "network",
    "query": {
     "query": "label_values(eth_future_block_proposals,network)"
    }
   },
   {
    "name": "scale",
    "label": "Scale Validator By",
    "query": "stake amount : _scaled,validator count :  "
   }
  ]
 },
 "panels": [
  { "title": "🖧 Network 🖧", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Quick Links",
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "\n- [open an issue](https://github.com/kilnfi/eth-validator-watcher/issues/new)\n- [github repository](https://github.com/kilnfi/eth-validator-watcher)\n- [beaconcha.in](https://beaconcha.in/)\n- [bageth.xyz](https://www.bageth.xyz/)\n- [etherscan.io](https://etherscan.io/)"
   }
  },
  {
   "title": "Epoch",
   "type": "stat",
   "description": "Ethereum epoch",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(eth_epoch{network=\"${network}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slot",
   "type": "stat",
   "description": "Ethereum slot",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(eth_slot{network=\"${network}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Epoch completion",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(eth_slot{network=\"${network}\"}) % 32",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ETH price",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(eth_current_price_dollars{network=\"${network}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Entry Queue Time",
   "type": "stat",
   "description": "Estimation of the entry queue time. Add ~12 hours for actual entry time.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((max(eth_pending_deposits_value{network=\"$network\"}) / 1e9) * (12*32)) / 256",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "🧱 Performances 🧱", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Active Validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(eth_validator_status${scale}_count{status=~\"active_ongoing|active_exiting\", scope=\"scope:all-network\", network=\"${network}\"} or vector(0))",
     "legendFormat": "network"
    },
    {
     "expr": "max(eth_validator_status${scale}_count{status=~\"active_ongoing|active_exiting\", scope=\"scope:watched\", network=\"${network}\"} or vector(0))",
     "legendFormat": "watched"
    }
   ]
  },
  {
   "title": "Assets under management",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(eth_validator_status_scaled_count{status=~\"active_ongoing|active_exiting\", scope=\"scope:all-network\", network=\"${network}\"} or vector(0)) * max(eth_current_price_dollars{network=\"${network}\"}) * 32",
     "legendFormat": "network"
    },
    {
     "expr": "max(eth_validator_status_scaled_count{status=~\"active_ongoing|active_exiting\", scope=\"scope:watched\", network=\"${network}\"} or vector(0)) * max(eth_current_price_dollars{network=\"${network}\"}) * 32",
     "legendFormat": "watched"
    }
   ]
  },
  {
   "title": "Healthiness",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 4, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(avg_over_time(eth_consensus_rewards_rate{scope=\"scope:all-network\", network=\"${network}\"}[$__interval]))",
     "legendFormat": "network"
    },
    {
     "expr": "max(avg_over_time(eth_consensus_rewards_rate{scope=\"scope:watched\", network=\"${network}\"}[$__interval]))",
     "legendFormat": "watched"
    }
   ]
  },
  {
   "title": "Block Missed",
   "type": "stat",
   "description": "Block proposals expected from the watched keys within the next 2 epochs. This signal can be used to know when to upgrade/perform operations on your Ethereum validation stack.",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(increase(eth_missed_block_proposals_finalized_total{scope=\"scope:all-network\", network=\"${network}\"}[$__range]))",
     "legendFormat": "network"
    },
    {
     "expr": "max(increase(eth_missed_block_proposals_finalized_total{scope=\"scope:watched\", network=\"${network}\"}[$__range]))",
     "legendFormat": "watched"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "expr": "eth_pending_deposits_count{network=\"$network\"}",
     "legendFormat": "Deposits"
    },
    {
     "expr": "eth_pending_consolidations_count{network=\"$network\"}",
     "legendFormat": "Consolidations"
    },
    {
     "expr": "eth_pending_withdrawals_count{network=\"$network\"}",
     "legendFormat": "Withdrawals"
    }
   ]
  },
  {
   "title": "Slashed Validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(eth_slashed_validators{scope=\"scope:all-network\", network=\"${network}\"} or vector(0))",
     "legendFormat": "network"
    },
    {
     "expr": "max(eth_slashed_validators{scope=\"scope:watched\", network=\"${network}\"} or vector(0))",
     "legendFormat": "watched"
    }
   ]
  },
  {
   "title": "Future Proposals",
   "type": "stat",
   "description": "Block proposals expected from the watched keys within the next 2 epochs. This signal can be used to know when to upgrade/perform operations on your Ethereum validation stack.",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(eth_future_block_proposals{scope=\"scope:all-network\", network=\"${network}\"})",
     "legendFormat": "network"
    },
    {
     "expr": "max(eth_future_block_proposals{scope=\"scope:watched\", network=\"${network}\"})",
     "legendFormat": "watched"
    }
   ]
  },
  {
   "title": "Share of the network",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((max(eth_validator_status_scaled_count{status=~\"active_ongoing|active_exiting\", scope=\"scope:all-network\", network=\"${network}\"}) or vector(0)) / (max(eth_validator_status_scaled_count{status=~\"active_ongoing|active_exiting\", scope=\"scope:all-network\", network=\"${network}\"}) or vector(0))) * 100.0",
     "legendFormat": "network"
    },
    {
     "expr": "((max(eth_validator_status_scaled_count{status=~\"active_ongoing|active_exiting\", scope=\"scope:watched\", network=\"${network}\"}) or vector(0)) / (max(eth_validator_status_scaled_count{status=~\"active_ongoing|active_exiting\", scope=\"scope:all-network\", network=\"${network}\"}) or vector(0))) * 100.0",
     "legendFormat": "watched"
    }
   ]
  },
  {
   "title": "Watched Validator Types",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (type) (eth_validator_type${scale}_count{scope=\"scope:watched\"})",
     "legendFormat": "0x0{{type}}"
    }
   ]
  },
  {
   "title": "Network Validator Types",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (type) (eth_validator_type${scale}_count{scope=\"scope:all-network\"})",
     "legendFormat": "0x0{{type}}"
    }
   ]
  },
  {
   "title": "Queued Validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(eth_pending_deposits_value{network=\"${network}\"}) / (32*1e9)",
     "legendFormat": "network"
    }
   ]
  },
  {
   "title": "Block Proposed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(increase(eth_block_proposals_finalized_total{scope=\"scope:all-network\", network=\"${network}\"}[$__range]))",
     "legendFormat": "network"
    },
    {
     "expr": "max(increase(eth_block_proposals_finalized_total{scope=\"scope:watched\", network=\"${network}\"}[$__range]))",
     "legendFormat": "watched"
    }
   ]
  },
  {
   "title": "🔎 Watched keys compared to the rest of the network 🔎",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "Attestation Rate (real-time)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "max(eth_duties_rate${scale}{scope=\"scope:network\", network=\"${network}\"}) * 100.0",
     "legendFormat": "scope:network"
    },
    {
     "expr": "max(eth_duties_rate${scale}{scope=\"scope:watched\", network=\"${network}\"}) * 100.0",
     "legendFormat": "scope:watched"
    }
   ]
  },
  {
   "title": "Missed blocks last 24H (count)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "max(increase(eth_missed_block_proposals_finalized_total{scope=\"scope:network\", network=\"${network}\"}[24h]))",
     "legendFormat": "scope:network"
    },
    {
     "expr": "max(increase(eth_missed_block_proposals_finalized_total{scope=\"scope:watched\", network=\"${network}\"}[24h]))",
     "legendFormat": "scope:watched"
    }
   ]
  },
  {
   "title": "Untimely or bad source vote (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "max(eth_suboptimal_sources_rate{scope=\"scope:network\", network=\"${network}\"})",
     "legendFormat": "scope:network"
    },
    {
     "expr": "max(eth_suboptimal_sources_rate{scope=\"scope:watched\", network=\"${network}\"})",
     "legendFormat": "scope:watched"
    }
   ]
  },
  {
   "title": "Untimely or bad target vote (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "max(eth_suboptimal_targets_rate{scope=\"scope:network\", network=\"${network}\"})",
     "legendFormat": "scope:network"
    },
    {
     "expr": "max(eth_suboptimal_targets_rate{scope=\"scope:watched\", network=\"${network}\"})",
     "legendFormat": "scope:watched"
    }
   ]
  },
  {
   "title": "Missed attestations (count)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "max(eth_missed_attestations${scale}{scope=\"scope:network\", network=\"${network}\"})",
     "legendFormat": "scope:network"
    },
    {
     "expr": "max(eth_missed_attestations${scale}{scope=\"scope:watched\", network=\"${network}\"})",
     "legendFormat": "scope:watched"
    }
   ]
  },
  {
   "title": "Consecutive missed attestations (count)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 29 },
   "targets": [
    {
     "expr": "max(eth_missed_consecutive_attestations${scale}{scope=\"scope:network\", network=\"${network}\"})",
     "legendFormat": "scope:network"
    },
    {
     "expr": "max(eth_missed_consecutive_attestations${scale}{scope=\"scope:watched\", network=\"${network}\"})",
     "legendFormat": "scope:watched"
    }
   ]
  },
  {
   "title": "Untimely or bad head vote (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "expr": "max(eth_suboptimal_heads_rate{scope=\"scope:network\", network=\"${network}\"})",
     "legendFormat": "scope:network"
    },
    {
     "expr": "max(eth_suboptimal_heads_rate{scope=\"scope:watched\", network=\"${network}\"})",
     "legendFormat": "scope:watched"
    }
   ]
  }
 ]
}